name: Build mini2440

on:
  workflow_dispatch:
    inputs:
      board:
        description: "Select the board branch"
        required: true
        default: "smdk2440"
        type: choice
        options:
          - smdk2440
          - mini2440

jobs:
  build_mini2440:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.board }}
      name: Checkout

    - name: Building in docker ubuntu:16.04
      id: docker_1604
      #uses: actions/hello-world-docker-action@v2
      uses: phugin/actions@build-smdk2440
      with:
        board-name: ${{ inputs.board }}

    - name: Check output
      run: |
        ls -al ./output/images/

    #- name: "Release TODO"
