name: Build mini2440

on:
  workflow_dispatch:
    inputs:
      board:
        description: "Select the board branch"
        required: true
        default: "smdk2440"
        type: choice
        options:
          - smdk2440
          - mini2440

jobs:
  build_mini2440:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.board }}
      name: Checkout

    - name: Building in docker ubuntu:16.04
      id: docker_1604
      #uses: actions/hello-world-docker-action@v2
      uses: phugin/actions@build-smdk2440
      with:
        board-name: ${{ inputs.board }}

    - name: Check output
      id: checks
      run: |
        ls -al ./output/images/
        echo "build_tag=${{ inputs.board }}_$(date +"%Y.%m.%d")" >> ${GITHUB_OUTPUT}

    - name: Upload the images
      uses: ncipollo/release-action@main
      with:
        tag: ${{ steps.checks.outputs.build_tag }}
        artifacts: ./output/images/*
        allowUpdates: true
        removeArtifacts: false
        replacesArtifacts: true
        token: ${{ secrets.BUILDROOT_TOKEN }}
        body: |
          ### ${{ inputs.board }} image information
          - u-boot: 2012.04.01
          - kernel: 3.4.2
          - rootfs: busybox-1.22