name: Build mini2440

on:
  workflow_dispatch:

jobs:
  build_mini2440:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: "mini2440"
      name: Checkout

    - name: Building in docker ubuntu:16.04
      id: docker_1604
      #uses: actions/hello-world-docker-action@v2
      uses: phugin/actions@build-mini2440

    - name: Check output
      run: |
        ls -al ./output/images/

    #- name: "Release TODO"
